/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bloque4_1.gui;

/**
 *
 * @author Manu
 */
public class Main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    /**
     * Creates new form GuessTheNumber
     */
    public Main() {
        initComponents();
        centrarPantalla(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void centrarPantalla() {
        setLocationRelativeTo(null); 
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int numeroSecreto = generarAleatorio();
    
        String entrada = javax.swing.JOptionPane.showInputDialog(
            "He generado un numero aleatorio del 0 al 10, ¿Podrás adivinarlo?: ");

        while (entrada != null) {
            try {
                int numUsuario = Integer.parseInt(entrada);

                if (numUsuario == numeroSecreto) {
                    javax.swing.JOptionPane.showMessageDialog(null, 
                        "¡Correcto! Era " + numeroSecreto);
                    break; // Salir del bucle cuando adivine
                } else if (numUsuario < numeroSecreto) {
                    javax.swing.JOptionPane.showMessageDialog(null, 
                        "Demasiado bajo. Intenta de nuevo.");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(null, 
                        "Demasiado alto. Intenta de nuevo.");
                }

                entrada = javax.swing.JOptionPane.showInputDialog(
                    "Intenta otra vez (0-10): ");
            
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(null, 
                    "Por favor, introduce un número válido.");
                entrada = javax.swing.JOptionPane.showInputDialog(
                    "Intenta otra vez (0-10): ");
            }
        }

            // Si el usuario canceló (entrada == null)
        if (entrada == null) {
            javax.swing.JOptionPane.showMessageDialog(null, 
            "Juego cancelado. El número era " + numeroSecreto);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private int generarAleatorio() {
        int num = (int) (Math.random() * 10);
        return num; 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
