/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ejercicioFinal.gui;

import com.toedter.calendar.JDateChooser;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import org.netbeans.validation.api.AbstractValidator;
import org.netbeans.validation.api.Problems;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;
import org.netbeans.validation.api.ui.swing.ValidationPanel;



/**
 *
 * @author Manu
 */
public class AddHeroe extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddHeroe.class.getName());
    GestorHeroes gestor; 
    private static ValidationPanel panelValidacion; 

    /**
     * Creates new form AddHeroe
     */
    public AddHeroe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        gestor = (GestorHeroes) parent;  
        centrarPantalla(); 
        initButton(); 
        addListeners(); 
        validation(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        validationPanel1 = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(AddHeroe.class, "AddHeroe.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(AddHeroe.class, "AddHeroe.jLabel2.text")); // NOI18N

        jTextField1.setText(org.openide.util.NbBundle.getMessage(AddHeroe.class, "AddHeroe.Nombre.text")); // NOI18N
        jTextField1.setName("Nombre"); // NOI18N

        jButton1.setText(org.openide.util.NbBundle.getMessage(AddHeroe.class, "AddHeroe.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText(org.openide.util.NbBundle.getMessage(AddHeroe.class, "AddHeroe.jLabel3.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(AddHeroe.class, "AddHeroe.jLabel4.text")); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fuego", "Agua", "Aire", "Tierra" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        jDateChooser1.setName("Fecha de alta"); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicioFinal/img/fuego.png"))); // NOI18N
        jLabel5.setText(org.openide.util.NbBundle.getMessage(AddHeroe.class, "AddHeroe.jLabel5.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(validationPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1)
                                    .addComponent(jSpinner1)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jButton1)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(validationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validation() {
        ValidationGroup group = validationPanel1.getValidationGroup(); 
        
        group.add(jTextField1, new AbstractValidator<String>(String.class) {
            @Override
            public void validate(Problems problems, String compName, String model) {
                if (model == null || model.trim().isEmpty()) {
                    problems.add("El nombre del héroe es obligatorio");
                } else if (model.trim().length() < 3) {
                    problems.add("El nombre debe tener al menos 3 caracteres");
                } else if (!model.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$")) {
                    problems.add("El nombre solo puede contener letras");
                }
            }
        });

        group.add(jDateChooser1.getDateEditor().getUiComponent(), 
            new AbstractValidator<String>(String.class) {
                @Override
                public void validate(Problems problems, String compName, String model) {
                    if (model == null || model.trim().isEmpty()) {
                        problems.add("La fecha de alta es obligatoria");
                    }
                }
            }
        );
    }
    
    private void initButton() {
        jButton1.setEnabled(false);
        boolean textFilled = jTextField1.getText() != null && !jTextField1.getText().isBlank(); 
        boolean dateFilled = jDateChooser1.getDate() != null; 
        
        if (textFilled && dateFilled) {
            jButton1.setEnabled(true);
        }
    }
    
    private void addListeners() {
        // Listener para JTextField
        jTextField1.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) { initButton(); }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) { initButton(); }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) { initButton(); }
        });

        // Listener para JDateChooser
        jDateChooser1.addPropertyChangeListener("date", evt -> initButton());
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:     
        if (!existeHeroe(jTextField1.getText())) {
            gestor.addToTable(this.obtenerDatos());
            this.setVisible(false);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "El héroe ya existe en la tabla.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String opcion = (String) jComboBox1.getSelectedItem(); 
        switch (opcion) {
            case "Fuego" -> {
                String ruta = "/ejercicioFinal/img/fuego.png"; 
                ImageIcon icono = new ImageIcon(getClass().getResource(ruta));
                Image imagen = icono.getImage();
                jLabel5.setIcon(new ImageIcon(imagen));
            }
            case "Agua" -> {
                String ruta = "/ejercicioFinal/img/agua.png"; 
                ImageIcon icono = new ImageIcon(getClass().getResource(ruta));
                Image imagen = icono.getImage();
                jLabel5.setIcon(new ImageIcon(imagen));
            }
            case "Tierra" -> {
                String ruta = "/ejercicioFinal/img/tierra.png"; 
                ImageIcon icono = new ImageIcon(getClass().getResource(ruta));
                Image imagen = icono.getImage();
                jLabel5.setIcon(new ImageIcon(imagen));
            }
            case "Aire" -> {
                String ruta = "/ejercicioFinal/img/viento.png"; 
                ImageIcon icono = new ImageIcon(getClass().getResource(ruta));
                Image imagen = icono.getImage();
                jLabel5.setIcon(new ImageIcon(imagen));
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void centrarPantalla() {
        setLocationRelativeTo(null); 
    }
    
    public Object[] obtenerDatos() {
        String nombreHeroe = jTextField1.getText(); 
        String poder = (String) jComboBox1.getSelectedItem(); 
        int nivel = (int) jSpinner1.getValue(); 
        Date fechaAlta = (Date) jDateChooser1.getDate();
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy"); 
        String fechaFormateada = format.format(fechaAlta); 
 
        
        Object[] datos = {nombreHeroe, poder, nivel, fechaFormateada};    
        return datos;       
    }
    
    private boolean existeHeroe(String nombreHeroe) {
        for (int i = 0; i < gestor.model.getRowCount(); i++) {
            String nombre = gestor.model.getValueAt(i, 0).toString(); 
            if (nombre.equalsIgnoreCase(nombreHeroe)) {
                return true;
            }
        }
        return false;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AddHeroe dialog = new AddHeroe(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel1;
    // End of variables declaration//GEN-END:variables

}
