/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bloque3_2;

import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Manu
 */
public class TablaMonstruos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TablaMonstruos.class.getName());
    private DefaultTableModel model; 
    private final String[] TABLE_HEADERS = {"Nombre", "Tipo", "Poder"};
    private TableRowSorter<TableModel> sorter; 

    /**
     * Creates new form TablaMonstruos
     */
    public TablaMonstruos() {
        initComponents();
        setLocationRelativeTo(null); 
        initTable(); 
        initSorter(); 
        addTableClickListener(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(TablaMonstruos.class, "TablaMonstruos.jLabel1.text")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bloque3_2/img/robot.png"))); // NOI18N
        jLabel2.setText(org.openide.util.NbBundle.getMessage(TablaMonstruos.class, "TablaMonstruos.jLabel2.text")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bloque3_2/img/robot.png"))); // NOI18N
        jLabel3.setText(org.openide.util.NbBundle.getMessage(TablaMonstruos.class, "TablaMonstruos.jLabel3.text")); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Tipo", "Poder"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText(org.openide.util.NbBundle.getMessage(TablaMonstruos.class, "TablaMonstruos.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addGap(48, 48, 48))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void initTable() {
        model = new DefaultTableModel(null, TABLE_HEADERS); 
        jTable1.setModel(model);
    }
    
    public void initSorter() {
        sorter = new TableRowSorter<>(jTable1.getModel());
        jTable1.setRowSorter(sorter);
        
        sorter.setComparator(2, (o1, o2) -> {
            Integer num1 = Integer.parseInt(o1.toString());
            Integer num2 = Integer.parseInt(o2.toString());
            return num1.compareTo(num2);
        });
        
        sorter.setSortKeys(Arrays.asList(
            new RowSorter.SortKey(2, SortOrder.DESCENDING)
        ));
        sorter.sort();      
    }
    
    private void addTableClickListener() {
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int column = jTable1.getColumnModel().getColumnIndexAtX(evt.getX());
                
                if (column == 2 && model.getRowCount() > 0) {
                    mostrarMonstruoMasFuerte();
                }
            }
        });
    }
    
    private void mostrarMonstruoMasFuerte() {
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, 
                "No hay monstruos en la tabla", 
                "Tabla vacía", 
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        int maxPoder = -1;
        String nombreMasFuerte = "";
        String tipoMasFuerte = "";
        
        for (int i = 0; i < model.getRowCount(); i++) {
            int poder = Integer.parseInt(model.getValueAt(i, 2).toString());
            if (poder > maxPoder) {
                maxPoder = poder;
                nombreMasFuerte = model.getValueAt(i, 0).toString();
                tipoMasFuerte = model.getValueAt(i, 1).toString();
            }
        }
        
        String mensaje = String.format(
            "🏆 MONSTRUO MAS FUERTE 🏆\n\n" +
            "Nombre: %s\n" +
            "Tipo: %s\n" +
            "Poder: %d",
            nombreMasFuerte, tipoMasFuerte, maxPoder
        );
        
        JOptionPane.showMessageDialog(this, 
            mensaje, 
            "Monstruo mas Fuerte", 
            JOptionPane.INFORMATION_MESSAGE);
    }
        
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        generarMonstruos(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void generarMonstruos() {
        String[] nombres = {"Draco", "Hydra", "Goblin", "Troll", "Fénix", "Vampiro", "Golem", "Kraken", "Quimera", "Basilisco"};
        String[] tipos = {"Dragón", "Gigante", "Humanoide", "Bestia", "No-muerto", "Elemental"};

        for (int i = 0; i < 10; i++) {
            int indiceNombre = (int) (Math.random() * nombres.length);
            int indiceTipo = (int) (Math.random() * tipos.length);
            int poder = (int) (Math.random() * 100);

            String nombre = nombres[indiceNombre];
            String tipo = tipos[indiceTipo];

            Object[] row = {nombre, tipo, poder};
            model.addRow(row);
        }
    }
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TablaMonstruos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
