/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica5ConLib.gui;

import java.time.LocalDate;

/**
 *
 * @author Manu
 */
public class CumpleañosFeliz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CumpleañosFeliz.class.getName());

    /**
     * Creates new form CumpleañosFeliz
     */
    public CumpleañosFeliz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCalendarComboBox1 = new de.wannawork.jcalendar.JCalendarComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(CumpleañosFeliz.class, "CumpleañosFeliz.jLabel1.text")); // NOI18N

        jButton1.setText(org.openide.util.NbBundle.getMessage(CumpleañosFeliz.class, "CumpleañosFeliz.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addComponent(jCalendarComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jCalendarComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Obtener la fecha del JDateChooser
        java.util.Date date = jCalendarComboBox1.getDate();


        // Validar que se haya seleccionado una fecha
            if (date == null) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Por favor, selecciona una fecha de nacimiento.", 
                    "Fecha no seleccionada", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

        // Convertir java.util.Date a LocalDate
        LocalDate fechaIntroducida = date.toInstant()
            .atZone(java.time.ZoneId.systemDefault())
            .toLocalDate();

        LocalDate hoy = LocalDate.now();

        // Validar que la fecha no sea futura
        if (fechaIntroducida.isAfter(hoy)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "La fecha de nacimiento no puede ser futura.", 
                "Fecha inválida", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Calcular la edad usando Period (más preciso)
        java.time.Period periodo = java.time.Period.between(fechaIntroducida, hoy);
        int edad = periodo.getYears();

        // Calcular próximo cumpleaños
        LocalDate proximoCumple = fechaIntroducida.withYear(hoy.getYear());

        // Si el cumpleaños ya pasó este año, calcular para el año siguiente
        if (proximoCumple.isBefore(hoy) || proximoCumple.isEqual(hoy)) {
            proximoCumple = proximoCumple.plusYears(1);
        }

        // Calcular días hasta el próximo cumpleaños
        long numDias = java.time.temporal.ChronoUnit.DAYS.between(hoy, proximoCumple);

        // Mensaje especial si es hoy el cumpleaños
        String mensaje;
        if (numDias == 0) {
            mensaje = "¡Feliz cumpleaños! Hoy cumples " + edad + " años.";
        } else {
            mensaje = "Tienes " + edad + " años y faltan " + numDias + 
                      " día" + (numDias == 1 ? "" : "s") + " para tu siguiente cumpleaños.";
        }

        javax.swing.JOptionPane.showMessageDialog(this, mensaje);

    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CumpleañosFeliz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private de.wannawork.jcalendar.JCalendarComboBox jCalendarComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
