/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bloque3_3.gui;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Manu
 */
public class ListaDeTareasLocas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListaDeTareasLocas.class.getName());
    private static DefaultTableModel model; 
    private static TablaFiltrada tablaFiltrada; 
    private static final String[] TABLE_HEADERS = {"Tarea", "Prioridad"}; 
    /**
     * Creates new form ListaDeTareasLocas
     */
    public ListaDeTareasLocas() {
        initComponents();
        centrarVentana(); 
        initTable(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tarea", "Prioridad"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(ListaDeTareasLocas.class, "ListaDeTareasLocas.jLabel1.text")); // NOI18N

        jButton1.setText(org.openide.util.NbBundle.getMessage(ListaDeTareasLocas.class, "ListaDeTareasLocas.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bloque3_3/img/Fiesta.png"))); // NOI18N
        jLabel2.setText(org.openide.util.NbBundle.getMessage(ListaDeTareasLocas.class, "ListaDeTareasLocas.jLabel2.text")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bloque3_3/img/Fiesta.png"))); // NOI18N
        jLabel3.setText(org.openide.util.NbBundle.getMessage(ListaDeTareasLocas.class, "ListaDeTareasLocas.jLabel3.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(150, 150, 150))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void centrarVentana() {
        setLocationRelativeTo(null); 
    }
    
    private void initTable() {
        model = new DefaultTableModel(null, TABLE_HEADERS);
        jTable1.setModel(model);  
        cargaDatos(); 
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        jTable1.setRowSorter(sorter);
    }
    
    private void cargaDatos() {
        model.addRow(new Object[]{"Comprar leche", "Baja"});
        model.addRow(new Object[]{"Preparar informe", "Alta"});
        model.addRow(new Object[]{"Llamar cliente", "Media"});
        model.addRow(new Object[]{"Revisar emails", "Alta"});
        model.addRow(new Object[]{"Enviar facturas", "Media"});
        model.addRow(new Object[]{"Revisar agenda", "Baja"});
        model.addRow(new Object[]{"Hacer backup", "Alta"});
        model.addRow(new Object[]{"Organizar escritorio", "Baja"});
        model.addRow(new Object[]{"Actualizar software", "Alta"});
        model.addRow(new Object[]{"Llamar proveedor", "Media"});
        model.addRow(new Object[]{"Preparar presentación", "Alta"});
        model.addRow(new Object[]{"Limpiar bandeja de entrada", "Baja"});
        model.addRow(new Object[]{"Revisar proyecto X", "Alta"});
        model.addRow(new Object[]{"Enviar correo a cliente", "Media"});
        model.addRow(new Object[]{"Planificar reunión", "Alta"});
        model.addRow(new Object[]{"Actualizar agenda", "Baja"});
        model.addRow(new Object[]{"Revisar presupuestos", "Media"});
        model.addRow(new Object[]{"Redactar informe semanal", "Alta"});
        model.addRow(new Object[]{"Hacer llamadas pendientes", "Media"});
        model.addRow(new Object[]{"Archivar documentos", "Baja"});
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        abrirVentana();       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void abrirVentana() {
        tablaFiltrada = new TablaFiltrada(this, true); 
        filtrarTabla(); 
        tablaFiltrada.setVisible(true);
    }
    
    private void filtrarTabla() {
        for (int i = 0; i < model.getRowCount(); i++) {
            String prioridad = model.getValueAt(i, 1).toString();
            if (prioridad.equalsIgnoreCase("Alta")) {
                Object[] fila = new Object[model.getColumnCount()];
                for (int j = 0; j < model.getColumnCount(); j++) {
                    fila[j] = model.getValueAt(i, j);
                }
                tablaFiltrada.aniadirTabla(fila);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ListaDeTareasLocas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
